name: "Rollback Release"
description: "Rollback a git release/tag. Useful for cleaning failed build/publish processes."
author: "Author.io"
branding:
  icon: "tag"
  color: "red"
inputs:
  release_id:
    description: The Github release ID.
    required: false
  tag:
    description: The tag associated with the release.
    required: false
  delete_orphan_tag:
    description: If the release does not exist but the tag does, setting this to true will remove the tag.
    required: false
outputs:
  release_id:
    description: Returns the ID of the release.
  tag:
    description: The tag associated with the release.
runs:
  using: "node18"
  main: "dist/index.js"
